### ISSUE TITLE
conf file suggestion

### ISSUE THREAD

**Issue by cononco99** [philliphall/plaid2qfx#2]
Since there's only one thing thing that really needs to be confidential in the conf file ( the secret ), it would probably make more sense to enter that at runtime (instead of the key being used to decrypt the file) and leave the file unencrypted.   This has a number of advantages:
* The user has only one secret key to hold on to: the plaid client API secret, instead of two: the client API secret and the randomly generated key.
* The code is simpler.  In fact you can eliminate the configparser_crypt dependency altogether.
* The config file becomes human readable and one line shorter.

**Comment by philliphall** [comment]
Simplicity is good, so I like where your head is at. Some additional thoughts to compare...

- I would also consider the Plaid access tokens sensitive since they grant persistent access to users' bank accounts. As currently configured, the users never even see them, and they can't be accessed outside of the script's runtime memory. 
- If I were to 'production-ize' this as a web app, it would operate with a statically configured Plaid secret, but need to isolate the encryption of each user's access tokens independently. Which I guess would be some rework either way. But then, I don't know that there are enough of us weirdos left using QFX to justify doing any of that...
- Human readable and editable config sure does make yours and my use cases a lot easier - no need to write fancy options for removing old accounts or updating any details.

**Comment by cononco99** [comment]
following up....

- The plaid access tokens only grant access to users' accounts to someone who knows the client id and client secret : see https://stackoverflow.com/a/70329767/509928 and https://stackoverflow.com/a/74225783/509928 (both answers written by the same person, "alex", whose stackoverflow profile says that he's with Plaid : https://stackoverflow.com/users/1533263/alex
- Having both a client api secret (from plaid) and a randomly generated key actually is less secure than having only the client api secret since having either one gives access to the client api secret.
- I submitted a PR to remove the encryption.

**Comment by philliphall** [comment]
Do you trust it enough to send me an access_token or two for me to test and verify I cannot access your data with it from my plaid dev account?


Thanks,
Phil Hall
________________________________

**Comment by cononco99** [comment]
I'd be OK with that.   Would verifying that you cannot access your data with the access_token that I send you be enough to accept the PR?

**Comment by philliphall** [comment]
Resolved via pull 10/09/2023. Thank you!
